<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Information</title>
    <?php echo ($this->getChild('head')->toHtml()); ?>
</head>

<body>
    <div>
        <?php echo ($this->getChildHtml('header')); ?>
    </div>
    
    <div>
        <?php echo ($this->getChildHtml('messages')); ?>
    </div>
    
    <div>
        <?php echo ($this->getChildHtml('footer')); ?>
    </div>
    <div>
        <?php echo ($this->getChildHtml('content')); ?>
    </div>
</body>

</html>