<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Information</title>
    <?php echo ($this->getChild('head')->toHtml()); ?>
</head>

<body>
    <div>
        <?php echo ($this->getChild('header')->toHtml()); ?>
    </div>
    <div>
        <?php echo ($this->getChild('footer')->toHtml()); ?>
    </div>
    <div>
        <?php echo ($this->getChild('messages')->toHtml()); ?>
    </div>
    <div>
        <?php echo ($this->getChild('content')->toHtml()); ?>
    </div>
    <div>
        <?php echo ($this->getChild('left')->toHtml()); ?>
    </div>
</body>

</html>