<?php 
 $data = Mage::getModel("Calculator/Calculor")->getCollection();

?>
<table border="1px">
<td><a href="<?php echo $this->getUrl('Calculator/index/form/');?>"><button>Add</button></a></td> 
<?php foreach ($data->getData() as $item) {?>
    <tr>
   <td><?php echo $item->getCalulatorId();?></td>   
   <td><?php echo $item->getCalculatorName();?></td>   
  
   <td><a href="<?php echo $this->getUrl('calculator/index/form/');?>?id=<?php echo $item->getCalculatorId(); ?>"><button>Update</button></a></td>   
   <td><a href="<?php echo $this->getUrl('calculator/index/delete/')?>?id=<?php echo $item->getCalculatorId()  ?>"><button>Delete</button></a></td>   
</tr>
<?php }?>
</table>
