
<footer class="footer">
    <div class="footer-content">
        <div class="footer-section about">
            <h3 style="font-size:1.8vw">About Us</h3>
            <p style="font-size:1.4vw">Welcome to Marketplace Platform the <br> ultimate destination for buyers and sellers <br> to connect, discover unique products, and create fulfilling shopping experiences.</p>
        </div>
        <div class="footer-section contact">
            <h3 style="font-size:1.8vw">Contact Us</h3>
            <p style="font-size:1.4vw">Email: info@example.com<br>Phone: 123-456-7890</p>
        </div>
        <div class="footer-section links">
            <h3 style="font-size:1.8vw">Quick Links</h3>
            <ul style="font-size:1.5vw">
                <li><a href="#">Visit Us</a></li>
                <li><a href="#">Contect</a></li>
                <li><a href="#">Know More</a></li>
                <li><a href="#">About Us</a></li>
            </ul>
        </div>
    </div>
    <div class="footer-bottom" style="font-size:1.2vw">
        &copy; 2024 Your Company. All rights reserved.
    </div>
</footer>
