<?php $data = $this->getCategory(); ?>


  <div class="title">Category Information</div>
    <form action="<?php echo $this->getUrl('admin/catalog_category/save') ?>">
        <div class="row">
            <label for="name">Name : </label>
            <input type="text" name="catalog_category[category_name]" id="name">
        </div>
        <div class="row">
            <label for="status" >Status : </label>
            <input type="text" name="catalog_category[status]" id="status">
        </div>

        <div class="row">
            <input type="submit" value="Submit">
        </div>
    </form>
