<html>
    <body>
        <h1>
            CONTENT
        </h1>
        <?php
    //    echo  $this->getRequest()->getparams("id");
   
    
       $productModel = Mage::getModel("product/product")->load(10);
       echo "<pre>";
      
      
       print_r($productModel);
       //print_r($productmodel);
       print_r($productModel->getId() . "<br>");
        print_r($productModel->getProductName());
        print_r($productModel->getSku());
        ?>
    </body>
</html>