<header class="header-fixed" style=" margin-left:0%; padding-left:0%;">

	<div class="header-limiter" style=" margin-left:0%; padding-left:0%;">
		<h1><img src="<?php echo Mage::getImagePath('')?>"></h1>
		<nav style="font-size:1.5vw">
			<a href="#">Home</a>
			<a href="#">Blog</a>
			<a href="#">Pricing</a>
			<a href="#">About</a>
			<a href="#">Faq</a>
			<a href="#">Contact</a>
		</nav>

	</div>

</header>