 <div class="logoContainer">
   <div class="topnav">
     <div class="logo">
       <img src="<?php echo Mage::getBaseUrl('Skin/image/logo.jpg') ?>" alt="Logo" width="55" height="40">
     </div>
     <div>
     <a class="active" href="#home">Home</a>
     <a href="#news">News</a>
     <a href="#contact">Contact</a>
     <a href="#about">About</a>
     <a href="#about">Images</a>
</div>
   </div>

   <div style="padding-left:16px">
     <h2></h2>
     <p></p>
   </div>