<?php $js = $this->getJs(); ?>
<?php if(count($js)): ?>
    <?php foreach($js as $_js): ?>
        <script type="text/javascript" src="<?php echo $_js; ?>" ></script>
    <?php endforeach; ?>
<?php endif; ?>

<?php $css = $this->getCss(); ?>
<?php if(count($css)): ?>
    <?php foreach($css as $_css): ?>
        <style type="" href="<?php echo $_css; ?>"></style>
    <?php endforeach; ?>
<?php endif; ?>