<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <?php $this->getChildHtml('head') ?>
</head>
<body>
    <div class="header"><?php $this->getChildHtml('header') ?></div>

    <div class="contect"><?php $this->getChildHtml('content') ?>
    <div>
        <?php echo $this->getChild('messages')->toHtml ();?>
    </div>    
        <!-- <div class="left">left</div> -->
        <!-- <div class="middle">middle</div> -->
        <!-- <div class="right">right</div> -->
    </div>
    <div class="footer"><?php $this->getChildHtml('footer') ?></div>
</body>
</html>