<div class="form">
    <h2 style="color:#FFF">Registration Form</h2>
    <form action="<?php echo $this->getUrl('customer/account/save') ?>" method="post">
        <div class="row">
            <!-- <label for="customer_id">Customer ID:</label> -->
            <input hidden type="text" id="customer_id" name="customer[customer_id]" class="form-control">
        </div>
        
        <div class="row">
            <label for="customer_email">Customer Email:</label>
            <input type="email" id="customer_email" name="customer[customer_email]" class="form-control">
        </div>
        
        <div class="row">
            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="customer[first_name]" class="form-control">
        </div>
        
        <div class="row">
            <label for="last_name">Last Name:</label>
            <input type="text" id="last_name" name="customer[last_name]" class="form-control">
        </div>

        <div class="row">
            <label for="password">Password:</label>
            <input type="password" id="password" name="customer[password]" class="form-control" required>
        </div>
        
        <div class="row">
            <label for="billing_address">Billing Address:</label>
            <input type="text" id="billing_address" name="customer[billing_address]" class="form-control">
        </div>
        
        <div class="row">
            <label for="billing_city">Billing City:</label>
            <input type="text" id="billing_city" name="customer[billing_city]" class="form-control">
        </div>
        
        <div class="row">
            <label for="billing_region">Billing Region:</label>
            <input type="text" id="billing_region" name="customer[billing_region]" class="form-control">
        </div>
        
        <div class="row">
            <label for="billing_country">Billing Country:</label>
            <input type="text" id="billing_country" name="customer[billing_country]" class="form-control">
        </div>
        
        <div class="row">
            <label for="billing_phone">Billing Phone:</label>
            <input type="tel" id="billing_phone" name="customer[billing_phone]" class="form-control">
        </div>
        
        <div class="row">
            <label for="shipping_address">Shipping Address:</label>
            <input type="text" id="shipping_address" name="customer[shipping_address]" class="form-control">
        </div>
        
        <div class="row">
            <label for="shipping_city">Shipping City:</label>
            <input type="text" id="shipping_city" name="customer[shipping_city]" class="form-control">
        </div>
        
        <div class="row">
            <label for="shipping_region">Shipping Region:</label>
            <input type="text" id="shipping_region" name="customer[shipping_region]" class="form-control">
        </div>
        
        <div class="row">
            <label for="shipping_country">Shipping Country:</label>
            <input type="text" id="shipping_country" name="customer[shipping_country]" class="form-control">
        </div>
        
        <div class="row">
            <label for="shipping_phone">Shipping Phone:</label>
            <input type="tel" id="shipping_phone" name="customer[shipping_phone]" class="form-control">
        </div>
        
        <div class="row">
            <label for="default">Default:</label>
            <input type="checkbox" id="default" name="customer[default]" class="form-control">
        </div>
        
        <div class="button">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
    </form>
</div>
