<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category Form</title>
</head>

<body>
    <form action="">
        <div class="row">
            <label for="name">Name : </label>
            <input type="text" name="catalog_product[name]" id="name">
        </div>
        <div class="row">
            <label for="status">Status : </label>
            <input type="text" name="catalog_product[status]" id="status">
        </div>

        <div class="row">
            <input type="submit" value="Submit">
        </div>
    </form>
</body>

</html>