<html>

<head>
    <title>MVC</title>
    <?php echo $this->getChild('head')->toHtml(); ?>
</head>

<body>
    <h1>
        <pre>  <div><?php echo $this->getChild('header')->toHtml(); ?> </div>
            <div><?php echo $this->getChild('content')->toHtml(); ?> </div>
            <div><?php echo $this->getChild('messages')->toHtml(); ?> </div>
            <div><?php echo $this->getChild('footer')->toHtml(); ?> </div>
            <div><?php echo $this->getChild('left')->toHtml(); ?> </div>
        </h1>
    </body>
</html>